import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { Toaster } from "react-hot-toast";
import { SessionProvider } from "next-auth/react";
import Providers from "@/components/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <GoogleOAuthProvider clientId="1060861804241-3q08iprj3j6gghdn3g4lbjdeh54496q9.apps.googleusercontent.com">
          <body className={inter.className}>
            {children}
            <Toaster />
          </body>
        </GoogleOAuthProvider>
      </Providers>
    </html>
  );
}
